### ISSUE TITLE
AmPeace.baf install error

### ISSUE THREAD

**Issue by NEXAnomaly** [RoxanneSHS/SandrahRtF#19]
Getting an install failure late into the EET setup. Can provide mod list and logs

C:\Games\Baldur's Gate Trilogy>Check Requirements for EET (Sandrah Saga II - Return to Faerun) was installed successfully.
RTF Movies and Sounds (Sandrah Saga II - Return to Faerun) was installed successfully.
Sandrah Return To Faerun Areas (Sandrah Saga II - Return to Faerun) was installed successfully.
Sandrah Return To Faerun Area Modifications (Sandrah Saga II - Return to Faerun) was installed successfully.
Sandrah Return To Faerun Creatures (Sandrah Saga II - Return to Faerun) was installed successfully.
Sandrah Return To Faerun Items and Stores (Sandrah Saga II - Return to Faerun) was installed successfully.

WARNING: internal label [48] not found in processed DLG [AMBAR01]
WARNING: EXTEND_BOTTOM state #48 out of range 0-44, SKIPPED
Sandrah Return To Faerun Compiles (Sandrah Saga II - Return to Faerun) was installed with warnings.

ERROR: error loading [SandrahRTF/AreaMod/AmPeace.baf]
ERROR: Unix.Unix_error(20, "stat", "SandrahRTF/AreaMod/AmPeace.baf")
Sandrah RtF Cross Mod Contents (Sandrah Saga II - Return to Faerun) was not installed due to errors.

**Comment by RoxanneSHS** [comment]
Sorry, a mistake I just made in the latest update...just move the file AmPeace.baf from SandrahRTF/baf to SandrahRTF/AreaMod in your BG2EE directory and try again.

**Comment by RoxanneSHS** [comment]
Fixed the issue in latest update.

**Comment by NEXAnomaly** [comment]
Thank you Roxanne you're a legend
